import { GeneratedFile } from "../../core/domain/generatedFile.js";
import { EntityConfig, ProjectConfig } from "../../core/domain/projectConfig.js";
import { GenerationContext, StackPluginContract } from "../../core/domain/pluginContract.js";

export class NestJsPlugin implements StackPluginContract {
  readonly name = "typescript-nestjs";
  readonly language = "typescript";
  readonly framework = "nestjs";
  readonly capabilities = {
    entities: true,
    crud: true,
    dto: true,
    validation: true,
    pagination: true,
    auth: ["jwt", "passport"],
    orm: ["prisma", "typeorm"],
    relations: true,
    extendExistingProject: false
  };

  async generateProject(_config: ProjectConfig): Promise<GeneratedFile[]> {
    return [];
  }

  async generateEntity(context: GenerationContext): Promise<GeneratedFile[]> {
    return context.entity ? [this.markerFile(context.entity, "entity")] : [];
  }

  async generateUseCase(context: GenerationContext & { name?: string }): Promise<GeneratedFile[]> {
    return context.entity ? [this.markerFile(context.entity, context.name ?? "usecase")] : [];
  }

  async generateController(context: GenerationContext): Promise<GeneratedFile[]> {
    return context.entity ? [this.markerFile(context.entity, "controller")] : [];
  }

  private markerFile(entity: EntityConfig, capability: string): GeneratedFile {
    const moduleName = pluralize(kebab(entity.name));
    return {
      path: `src/modules/${moduleName}/.arxgen-${capability}`,
      content: `Generated by ${this.name} ${capability} capability.
`
    };
  }
}

function kebab(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "module";
}

function pluralize(value: string): string {
  return value.endsWith("s") ? value : `${value}s`;
}
